package gt.edu.umg.ingenieria.sistemas.geometric_figures.view;



import gt.edu.umg.ingenieria.sistemas.geometric_figures.service.CircleService;
import gt.edu.umg.ingenieria.sistemas.geometric_figures.service.OvalService;
import gt.edu.umg.ingenieria.sistemas.geometric_figures.service.RectangleService;
import gt.edu.umg.ingenieria.sistemas.geometric_figures.service.SquareService;
import gt.edu.umg.ingenieria.sistemas.geometric_figures.service.TriangleService;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yunyor-PC
 */
public class VistaFigurasGeometricas extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
     String figura;
     String colorfigura;
     String colorborde;
     String formato;
    public VistaFigurasGeometricas() {
        initComponents();
        txt_cuadrado.setVisible(false);
        lbl_triangulo.setVisible(false);
        txt_triangulo.setVisible(false);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_cuadrado = new javax.swing.JLabel();
        txt_triangulo = new javax.swing.JTextField();
        txt_cuadrado = new javax.swing.JTextField();
        lbl_triangulo = new javax.swing.JLabel();
        uni = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fig = new javax.swing.JComboBox<>();
        colorfig = new javax.swing.JComboBox<>();
        bordefig = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lbl_cuadrado.setBackground(new java.awt.Color(255, 255, 255));

        txt_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_trianguloActionPerformed(evt);
            }
        });

        txt_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuadradoActionPerformed(evt);
            }
        });

        lbl_triangulo.setBackground(new java.awt.Color(0, 204, 204));
        lbl_triangulo.setText("Ingrese la altura");

        uni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mm", "cm", "mts", "km", " " }));
        uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccione la unidad de medida de la figura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(uni, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(uni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jLabel3.setText("Perimetro");

        jLabel4.setText("Area");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(310, 220));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Figuras Geometricas"));

        jLabel1.setText("Seleccione La Figura Geometrica");

        fig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuadrado", "Circulo", "Triangulo", "Rectangulo", "Ovalado" }));
        fig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                figActionPerformed(evt);
            }
        });

        colorfig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLANCO", "GRISCLARO", "GRIS", "GRISOSCURO", "NEGRO", "ROJO", "ROSADO", "ANARANJADO", " AMARILLO", "VERDE", "LILA", "TURQUESA", "AZUL" }));
        colorfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorfigActionPerformed(evt);
            }
        });

        bordefig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLANCO", "GRISCLARO", "GRIS", "GRISOSCURO", "NEGRO", "ROJO", "ROSADO", "ANARANJADO", " AMARILLO", "VERDE", "LILA", "TURQUESA", "AZUL" }));
        bordefig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordefigActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione el color del area");

        jLabel5.setText("Seleccione el color del borde");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorfig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(bordefig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fig, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bordefig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones sobre la Figura Geometrica"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PNG", "JPG" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear Imagen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Imprimir en pantalla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccione el formato de la imagen");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel6)
                    .addComponent(jButton1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Datos\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void figActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_figActionPerformed
        // TODO add your handling code here:
         figura = fig.getSelectedItem().toString();
        if(figura.equals("Cuadrado")){
            //figure=0;
            lbl_cuadrado.setText("Ingrese el lado del cuadrado");
            txt_cuadrado.setVisible(true);
            lbl_triangulo.setVisible(false);
            txt_triangulo.setVisible(false);          
        }
          if(figura.equals("Circulo")){
            //figure=0;
            lbl_cuadrado.setText("Ingrese Radio");
            txt_cuadrado.setVisible(true);
            lbl_triangulo.setVisible(false);
            txt_triangulo.setVisible(false);
       
        }
          if(figura.equals("Triangulo")){
            //figure=0;
            lbl_triangulo.setVisible(true);
            lbl_cuadrado.setText("Ingrese la base");
            txt_cuadrado.setVisible(true);     
            txt_triangulo.setVisible(true); 
        }
           if(figura.equals("Rectangulo")){
            //figure=0;
            lbl_triangulo.setVisible(true);
            lbl_cuadrado.setText("Ingrese la base");
            txt_cuadrado.setVisible(true);     
            txt_triangulo.setVisible(true); 
        }
           if(figura.equals("Ovalado")){
            //figure=0;
            lbl_triangulo.setVisible(true);
            lbl_cuadrado.setText("Ingrese eje mayor");
            lbl_triangulo.setText("Ingrese eje menor");
            txt_cuadrado.setVisible(true);     
            txt_triangulo.setVisible(true); 
        }
     
    }//GEN-LAST:event_figActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // TODO add your handling code here:
        switch(figura){
            case "Circulo":
                    CircleService circulo = new CircleService() ;                
                    circulo.CreateCircle(Float.parseFloat(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                    circulo.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(circulo.getPerimeter());
                    jTextField4.setText(circulo.getArea());
            break;
            case "Cuadrado":
                    SquareService cuadrado = new SquareService();
                    cuadrado.CreateSquare(Float.parseFloat(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                    cuadrado.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(cuadrado.getPerimeter());
                    jTextField4.setText(cuadrado.getArea());
                   
            break;
            case "Rectangulo":
                   RectangleService rectangulo = new RectangleService();
                    rectangulo.CreateRectangle(Float.parseFloat(txt_triangulo.getText()),Float.parseFloat(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                    rectangulo.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(rectangulo.getPerimeter());
                    jTextField4.setText(rectangulo.getArea());
            break;
            case "Triangulo":
                TriangleService triangulo = new TriangleService();
                    triangulo.CreateTriangle(Float.parseFloat(txt_cuadrado.getText()),Float.parseFloat(txt_triangulo.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                    triangulo.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(triangulo.getPerimeter());
                    jTextField4.setText(triangulo.getArea());
            break;
              case "Ovalado":
                OvalService ovalado = new OvalService();
                    ovalado.CreateOval(Float.parseFloat(txt_cuadrado.getText()),Float.parseFloat(txt_triangulo.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                    ovalado.getdrawFigure(jPanel2.getGraphics());
                    jTextField3.setText(ovalado.getPerimeter());
                    jTextField4.setText(ovalado.getArea());
            break;
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      switch(figura){
             case "Circulo":
                    CircleService circulo = new CircleService() ;                
                    circulo.CreateCircle(Float.parseFloat(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                    jTextField3.setText(circulo.getPerimeter());
                    jTextField4.setText(circulo.getArea());
                    circulo.getimage(jComboBox1.getSelectedItem().toString());
            break;
            case "Cuadrado":
                    SquareService cuadrado = new SquareService();
                    cuadrado.CreateSquare(Float.parseFloat(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
           
                    jTextField3.setText(cuadrado.getPerimeter());
                    jTextField4.setText(cuadrado.getArea());
                     cuadrado.getimage(jComboBox1.getSelectedItem().toString());
                   
            break;
            case "Rectangulo":
                   RectangleService rectangulo = new RectangleService();
                    rectangulo.CreateRectangle(Float.parseFloat(txt_triangulo.getText()),Float.parseFloat(txt_cuadrado.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                     rectangulo.getimage(jComboBox1.getSelectedItem().toString());
                    jTextField3.setText(rectangulo.getPerimeter());
                    jTextField4.setText(rectangulo.getArea());
            break;
            case "Triangulo":
                TriangleService triangulo = new TriangleService();
                    triangulo.CreateTriangle(Float.parseFloat(txt_cuadrado.getText()),Float.parseFloat(txt_triangulo.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                    triangulo.getimage(jComboBox1.getSelectedItem().toString());
                    jTextField3.setText(triangulo.getPerimeter());
                    jTextField4.setText(triangulo.getArea());
            break;
              case "Ovalado":
                OvalService ovalado = new OvalService();
                    ovalado.CreateOval(Float.parseFloat(txt_cuadrado.getText()),Float.parseFloat(txt_triangulo.getText()),colorfig.getSelectedItem().toString(),bordefig.getSelectedItem().toString(),uni.getSelectedItem().toString());
                  ovalado.getimage(jComboBox1.getSelectedItem().toString());
                    jTextField3.setText(ovalado.getPerimeter());
                    jTextField4.setText(ovalado.getArea());
            break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void colorfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorfigActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_colorfigActionPerformed

    private void bordefigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordefigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bordefigActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txt_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cuadradoActionPerformed

    private void txt_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_trianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_trianguloActionPerformed

    private void uniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFigurasGeometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFigurasGeometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFigurasGeometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFigurasGeometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFigurasGeometricas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bordefig;
    private javax.swing.JComboBox<String> colorfig;
    private javax.swing.JComboBox<String> fig;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbl_cuadrado;
    private javax.swing.JLabel lbl_triangulo;
    private javax.swing.JTextField txt_cuadrado;
    private javax.swing.JTextField txt_triangulo;
    private javax.swing.JComboBox<String> uni;
    // End of variables declaration//GEN-END:variables
}
